guard against CCI invocation API failure

diff --git a/.github/workflows/e2e.yml b/.github/workflows/e2e.yml
--- a/.github/workflows/e2e.yml
+++ b/.github/workflows/e2e.yml
@@ -29,6 +29,10 @@ jobs:
           --data "{\"branch\":\"main\",\"parameters\":{\"deno_sdk_import_url\":\"${IMPORT_URL}\"}}")
           echo $TEST_PAYLOAD;
           TEST_JOB_WORKFLOW_ID=$(echo $TEST_PAYLOAD | jq '.id');
+          if [ $TEST_JOB_WORKFLOW_ID = "null" ]; then
+            echo "Problem extracting job ID from invocation API call! Aborting.";
+            exit 1;
+          fi
           echo "e2e test workflow started with id: $TEST_JOB_WORKFLOW_ID"
           echo "TEST_JOB_WORKFLOW_ID=${TEST_JOB_WORKFLOW_ID}" >> $GITHUB_ENV
       - name: Wait for platform-devxp-test E2E run to complete
